version: '3.7'
services:
    reverse-proxy:
        container_name: traefik
        image: 'klingelnberg.azurecr.io/gearengine/traefik:${Traefik_Version}'
        restart: always
        networks:
            - internal-network
        command: '--api.insecure=true
            --providers.docker
            --providers.docker.network=gearengine-network
            --log.level=DEBUG'
        ports:
            - '80:80'
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
    mongo-database:
        container_name: mongo-ge
        image: 'klingelnberg.azurecr.io/gearengine/mongo:${Mongo_Service_Version}'
        restart: always
        ports:
            - '30041:27017'
        networks:
            - internal-network
        volumes:
            - 'mongodata:/data/db'
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
    messaging-service:
        container_name: active_mq-ge
        image: 'klingelnberg.azurecr.io/gearengine/activemq:${Active_MQ_Service_Version}'
        restart: always
        ports:
            - '30050:8161'
            - '30051:5672'
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
    production-machine-service:
        container_name: productionmachines.service-ge
        image: 'klingelnberg.azurecr.io/gearengine/productionmachines.service:${Production_Machines_Service_Version}'
        restart: always
        ports:
            - '30091:80'
        labels:
            - traefik.http.routers.production-machine-service.rule=PathPrefix(`/api/machines`)
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            MongoOptions__ConnectionString: 'mongodb://mongo-ge:27017'
            MongoOptions__DatabaseName: CorrectionLoop
            BaseUrlConfiguration__BaseUrl: '/api/machines'
        depends_on:
            - mongo-database
    production-machine-app:
        container_name: productionmachines.app-ge
        image: 'klingelnberg.azurecr.io/gearengine/productionmachines.app:${Production_Machines_App_Version}'
        restart: always
        ports:
            - '30092:80'
        labels:
            - traefik.http.routers.production-machine-app.rule=PathPrefix(`/web/machines`)
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            ServerConfiguration__ProductionMachineServiceUrl: 'http://productionmachines.service-ge:80'
            BaseUrlConfiguration__BaseUrl: '/web/machines'
        depends_on:
            - production-machine-service
    correction-loop-service:
        container_name: correctionloop-ge
        image: 'klingelnberg.azurecr.io/gearengine/clps.correctionloop:${Correction_Loop_Service_Version}'
        restart: always
        ports:
            - '31201:80'
        labels:
            - traefik.http.routers.correction-loop-service.rule=pathprefix(`/api/cls/v1`)
        networks:
            - internal-network
        volumes:
            - 'clslogs:/app/logs'
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            MongoOptions__ConnectionString: 'mongodb://mongo-ge:27017'
            MongoOptions__DatabaseName: CorrectionLoop
            ServerConfiguration__ProductionMachineServiceUrl: 'http://productionmachines.service-ge:80'
            MessageBrokers__Order__Hostname: active_mq-ge
            MessageBrokers__Order__Port: 5672
            MessageBrokers__Order__Username: admin
            MessageBrokers__Order__Password: admin
            MessageBrokers__Order__QueueName: 'topic://klbg.ge.CorrectionLoop.Order'
            MessageBrokers__Order__LinkName: KLBG.GearEngine.Services.CorrectionLoop.OrderService
            MessageBrokers__Order__ContainerId: correctionLoop-order-service-send
            MessageBrokers__Measurement__Hostname: active_mq-ge
            MessageBrokers__Measurement__Port: 5672
            MessageBrokers__Measurement__Username: admin
            MessageBrokers__Measurement__Password: admin
            MessageBrokers__Measurement__QueueName: 'topic://klbg.ge.CorrectionLoop.Measurement'
            MessageBrokers__Measurement__LinkName: KLBG.GearEngine.Services.CorrectionLoop.MeasurementService
            MessageBrokers__Measurement__ContainerId: correctionLoop-measurement-service-send
            MessageBrokers__CorrectionIncrement__Hostname: active_mq-ge
            MessageBrokers__CorrectionIncrement__Port: 5672
            MessageBrokers__CorrectionIncrement__Username: admin
            MessageBrokers__CorrectionIncrement__Password: admin
            MessageBrokers__CorrectionIncrement__QueueName: 'topic://klbg.ge.CorrectionLoop.Correction'
            MessageBrokers__CorrectionIncrement__LinkName: KLBG.GearEngine.Services.CorrectionLoop.MachineCorrectionService
            MessageBrokers__CorrectionIncrement__ContainerId: correctionLoop-machineCorrection-service-send
            MessageBrokers__ProcessDesignUpdate__Hostname: active_mq-ge
            MessageBrokers__ProcessDesignUpdate__Port: 5672
            MessageBrokers__ProcessDesignUpdate__Username: admin
            MessageBrokers__ProcessDesignUpdate__Password: admin
            MessageBrokers__ProcessDesignUpdate__QueueName: 'topic://klbg.ge.CorrectionLoop.ProcessDesignUpdate'
            MessageBrokers__ProcessDesignUpdate__LinkName: KLBG.GearEngine.Services.ProcessDesignUpdate
            MessageBrokers__ProcessDesignUpdate__ContainerId: process-design-update-send
            BaseUrlConfiguration__BaseUrl: '/api/cls/v1'
        depends_on:
            - mongo-database
            - messaging-service
            - production-machine-service
            - processdesign-reporting-service
    gear-corrector:
        container_name: gearcorrector-ge
        image: 'klingelnberg.azurecr.io/gearengine/gearcorrector:${Gear_Corrector_App_Version}'
        restart: always
        ports:
            - '31202:80'
        labels:
            - traefik.http.routers.gear-corrector.rule=PathPrefix(`/web/gear-corrector`)
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            ServerConfiguration__CorrectionLoopServiceUrl: 'http://correctionloop-ge:80'
            ServerConfiguration__ProductionMachineServiceUrl: 'http://productionmachines.service-ge:80'
            LanguageConfiguration__Default: en-US
            FeatureManagement__Beta: '${Gear_Corrector_Enable_Beta_Features}'
            BaseUrlConfiguration__BaseUrl: '/web/gear-corrector'
        depends_on:
            - correction-loop-service
            - production-machine-service
    clps-app:
        container_name: clpsapp-ge
        image: 'klingelnberg.azurecr.io/gearengine/clpsapp:${CLPS_App_Version}'
        restart: always
        ports:
            - '31203:80'
        labels:
            - traefik.http.routers.clps-app.rule=PathPrefix(`/web/clps-app`)
        networks:
            - internal-network
        volumes:
            - 'clslogs:/app/logs'
            - './clpslogs:/app/clpsAppLogs'
            - './backups:/backups'
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            ServerConfiguration__CorrectionLoopServiceLogsDirectory: /app/logs
            ServerConfiguration__CorrectionLoopServiceBackupDirectory: /backups
            ServerConfiguration__CorrectionLoopServiceUrl: 'http://correctionloop-ge:80'
            ServerConfiguration__ProductionMachineServiceUrl: 'http://productionmachines.service-ge:80'
            ServerConfiguration__ProductionMachineAppUrl: 'http://${Server_Name}:30092'
            ServerConfiguration__ProcessDesignReportServiceUrl: 'http://processdesignreporting.service-ge:80'
            RepositoryConfigurations__ConnectionString: 'mongodb://mongo-ge:27017'
            MessagingConfigurations__Hostname: active_mq-ge
            MessagingConfigurations__Port: 5672
            MessagingConfigurations__Username: admin
            MessagingConfigurations__Password: admin
            MessagingConfigurations__MeasurementQueueName: 'topic://klbg.ge.CorrectionLoop.Measurement'
            MessagingConfigurations__CorrectionIncrementQueueName: 'topic://klbg.ge.CorrectionLoop.Correction'
            MessagingConfigurations__ProcessDesignQueueName: 'topic://klbg.ge.CorrectionLoop.Order'
            MessagingConfigurations__LinkName: 'KLBG.GearEngine.Services.Clps.App'
            MessagingConfigurations__RecentActivityCount: 10
            BaseUrlConfiguration__BaseUrl: '/web/clps-app'
        depends_on:
            - mongo-database
            - messaging-service
            - production-machine-service
            - correction-loop-service
            - production-machine-app
            - processdesign-reporting-service
    processdesign-reporting-service:
        container_name: processdesignreporting.service-ge
        image: 'klingelnberg.azurecr.io/gearengine/processdesignreporting.service:${ProcessDesignReporting_Service_Version}'
        restart: always
        ports:
            - '31204:80'
        labels:
            - traefik.http.routers.processdesign-reporting-service.rule=PathPrefix(`/api/process-design`)
        networks:
            - internal-network
        logging:
            driver: json-file
            options: { max-size: 20m, max-file: '5' }
        environment:
            TZ: '${Time_Zone}'
            MongoOptions__ConnectionString: 'mongodb://mongo-ge:27017'
            MongoOptions__DatabaseName: ProcessDesign
            MessagingConfigurations__Hostname: "active_mq-ge"
            MessagingConfigurations__Port: 5672
            MessagingConfigurations__Username: "admin"
            MessagingConfigurations__Password: "admin"
            MessagingConfigurations__ProcessDesignUpdateQueueName: "topic://klbg.ge.CorrectionLoop.ProcessDesignUpdate"
            MessagingConfigurations__LinkName: "KLBG.GearEngine.Services.ProcessDesignUpdate"
            BaseUrlConfiguration__BaseUrl: '/api/process-design'
        depends_on:
            - mongo-database
networks:
    internal-network:
        driver: bridge
        name: gearengine-network
volumes:
    mongodata:
        driver: local
        name: mongodata
    clslogs:
        driver: local
        name: cls-logs
